spring:
  application:
    name: Notification
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/jobs?currentSchema=microservices
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    admin:
      properties:
        allow.auto.create.topics: true
  kafka-listener:
    container:
      concurrency: 3  # Максимальное количество потоков слушателей
    consumer:
      enable-auto-commit: false  # Отключение автоматического коммита
      auto-offset-reset: earliest
  liquibase:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password:

server:
  port: 8081